### PR TITLE
LPS-76583 Updates journal usages of aui:button

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by jkappler** [comment]
Hi @anthony-chu, we are getting this error with a poshi tests. Could you tell us please if the failure is real? Or maybe we have to change the functional test to adapt it to the new changes in the PR?

Let us know what you think. Thanks!

**Comment by anthony-chu** [comment]
hi @jkappler! sorry, this was my mistake. i made a mass change to some of our macros, and it should not have applied to how we save web content structures. i will try to send a test fix into master soon to fix this. i apologize for the inconvenience.

**Comment by jkappler** [comment]
no problem @anthony-chu, thanks for letting us know!

**Pull request merged**
