### PR TITLE
[TS] LPS-75797

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by ealonso** [comment]
Merged!! Thanks!!

**Comment by yuhai** [comment]
Hi @ealonso 

Hope you are well.

Since the fix came from subscription customer. I notice the fix didn't been merged to liferay-portal/master. Is there anything I need to do this?

Regards,
Hai

**Comment by ealonso** [comment]
Hey @yuhai,

It is automatically merged on central once all test are in green, please see: https://github.com/liferay/liferay-portal/pull/2266.

Regards,
Eudaldo.

**Comment by yuhai** [comment]
Thanks @ealonso , got it. 

Regards,
Hai

**Pull request closed without merging**
