### PR TITLE
LPS-77164

### PR DESCRIPTION
**Pull request by matethurzo**
Changing the structure related to an article can cause a validation error. In a more generic way UI allows the user to change the content in some cases that leads to an invalid state. Running the validations during staging will result in an exception causing the staging to fail, however the UI designed to work with the inconsistencies. this change is bypassing the validations when importing

### CODE REVIEW

**Comment by matethurzo** [comment]
ci:test

**Comment by ealonso** [comment]
Hey @matethurzo @zoltancsaszi,

Could be possible use "ExportImportThreadLocal.isImportInProcess()" instead of adding a new parameter to the methods?

Regards,
Eudaldo.

**Comment by zoltancsaszi** [comment]
Hey @ealonso,

That parameter was already there, we just renamed it to describe the actual purpose.
We can use the "ExportImportThreadLocal.isImportInProcess()" from the LocalServiceImpl, but the validate(formerly latestVersion) parameter should be deleted then since it wouldn't be used anymore.

Regards,
Zoli

**Comment by ealonso** [comment]
Hey @zoltancsaszi,

Could you please do that? remove the parameter from services and use ExportImportThreadLocal.isImportInProcess(). IMHO, I think is going to be more clear for the future.

Also, please add one commit with the changes in LocalServiceImpl and another commit with Auto generated files.

Thanks!!
Eudaldo.

**Comment by matethurzo** [comment]
will resend according to the discussion

**Pull request closed without merging**
