### PR TITLE
LPS-73630 Remove temp from table name since there is no ambiguity, add title column do be able to order by title

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by ealonso** [comment]
@anthony-chu @koor4356,

Do you know why those test are broken in every pull?

Regards,
Eudaldo.

**Comment by ealonso** [comment]
Merged!! Thanks!!

**Comment by koor4356** [comment]
@ealonso, Search icon is missing and I think it is related to this https://issues.liferay.com/browse/LPS-74153.

**Comment by ealonso** [comment]
@koor4356, Thanks you very much!!

**Pull request closed without merging**
