### PR TITLE
J cords lps 73925 revised

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-73925
https://issues.liferay.com/browse/LPP-26392

This is continued from here: liferay/com-liferay-journal#430
I've changed the logic to keep the isHead logic, but added "latest" for isLatestArticle.

The expected behavior for search in the Web Content Portlet is:
A User can search for latest version of the article if it is Approved, Pending, Draft, Expired, ... but not In-Trash.

### CODE REVIEW

**Comment by joshuacords** [comment]
ci:reopen

**Comment by joshuacords** [comment]
ci:retest

**Comment by joshuacords** [comment]
I closed this by mistake.

**Comment by joshuacords** [comment]
Hello @ealonso, Take a look at these changes when you have a change.

**Comment by ealonso** [comment]
Merged!! Thanks!!

**Pull request closed without merging**
