### PR TITLE
LPS-60792 removing scopeType reset

### PR DESCRIPTION
**Pull request by balazssk**
Fixing a bad commit.

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:retest

**Comment by ealonso** [comment]
Hey @matethurzo,

Could you please take a look at it? See https://github.com/matethurzo/liferay-portal/pull/1751, they are removing 2 lines that you added.

Thanks!!
Eudaldo.

**Comment by zsigmondrab** [comment]
Hi @matethurzo,

this issues has a long story. A fix has been pushed there which you have extended with those two lines, however, those lines make the fix wrong. I've removed that in the past, sent a pull request (https://github.com/matethurzo/liferay-portal/pull/1303), however, that has never gone to the source because after months I deleted the branch accidentally.

Thanks,
Zsigmond

**Comment by ealonso** [comment]
Hey @matethurzo,

Have you had the time to look at it?

Regards,
Eudaldo.

**Comment by matethurzo** [comment]
@ealonso @zsigmondrab @balazssk hey guys, I've checked this. the problem is if we remove those lines it will cause a regression to other portlets.

this change under a certain condition will change the portlet data context's scope type to company but if we don't change it back to the original one, other portlets will be using that too.

We need to look for a different solution.

We need to find the root cause why does it help if we remove it, maybe we need a different set of conditions when this is working.

**Comment by ealonso** [comment]
@balazssk please see @matethurzo comment

**Pull request closed without merging**
