### PR TITLE
LPS-72555

### PR DESCRIPTION
**Pull request by holatuwol**
Resend of https://github.com/liferay/com-liferay-journal/pull/321

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:retest

**Comment by holatuwol** [comment]
ci:retest

**Comment by holatuwol** [comment]
Conflicts, need to resolve.

**Pull request closed without merging**
