### PR TITLE
LPS-71213 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @jbalsas,

Could you please take a look at it?

Thanks!!!
Eudaldo.

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
@carloslancha 

Could you please take a look to source formatter errors?

Regards,
Eudaldo.

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
https://github.com/liferay/com-liferay-journal/pull/270

**Pull request closed without merging**
