### PR TITLE
LPS-70608 Avoid execute the upgrade for current DXP users

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @achaparro,

Could you please check the source formatter error?

Thanks!!
Eudaldo.

**Comment by achaparro** [comment]
Sorry @ealonso, it's fixed now!

Thanks.

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
Merged!!!

**Pull request closed without merging**
