### PR TITLE
LPS-68104 Group By ID so only unique entries are returned

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey @juliocamarero,

I'm still a bit unclear on the new workflow for sub-repositories. I've sent the pull request here and assigned you the LPS, but let me know if you want something different in the future.

Thanks.

/cc @ChrisKian

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Resend on ee-7.0.x

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Hi guys, 

I just reverted this fix based on Shuyang's comment: https://github.com/brianchandotcom/liferay-portal-ee/pull/15014#issuecomment-259416265

thank you!

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Hey @jonathanmccann 

I reverted this fix based on Shuyang's comment: brianchandotcom/liferay-portal-ee#15014 (comment)

Could you please have a look?

thank you!

**Pull request closed without merging**
