### PR TITLE
LPS-73759

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @jonathanmccann,

One question, what happends with the users that are using this property in milliseconds?, maybe we need an upgrade process for it?

Regards,
Eudaldo.

**Comment by jonathanmccann** [comment]
@ealonso,

I can definitely add in an upgrade process though if you would like. I wasn't sure how necessary it would be so I tried to keep this change as simple as possible.

**Comment by jonathanmccann** [comment]
I just tested by having a long value for the checkInterval, applying my change, and then updating the value. In the database, the value gets properly swapped over to an int, but you are right that if users do not recognize that this changed their interval will be off.

**Comment by ealonso** [comment]
@jonathanmccann 

Ok, Could you please send me another pull request with the upgrade process?

Thanks!!
Eudaldo.

**Comment by jonathanmccann** [comment]
https://github.com/liferay/com-liferay-journal/pull/411

**Pull request closed without merging**
