### PR TITLE
LPS-68871 missing imports

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:retest

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Pull request submitted to https://github.com/pavel-savinov/com-liferay-journal/pull/1. [See changes here.](https://github.com/liferay/com-liferay-journal/compare/1716e41~5...1716e41) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
