### PR TITLE
LPS-72716 SQL crash during search in web content with multiple structure

### PR DESCRIPTION
**Pull request by rimisaadouwork**
Hi,

Could you please review this commit.
https://issues.liferay.com/browse/LPS-72716

Thanks!

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @rimisaadouwork,

There is a source formatter error, Could you please fix it and resend?

Regards,
Eudaldo

**Comment by rimisaadouwork** [comment]
Hi @ealonso,

Could you please help me. When I run gw formatSource I don't get any error or warning. 
I only changed false in true. So I don't understand why the test is failing.

Thanks!

**Comment by ealonso** [comment]
Please see: https://github.com/liferay/com-liferay-journal/pull/334

**Comment by ealonso** [comment]
@rimisaadouwork https://github.com/liferay/com-liferay-journal/pull/334

**Pull request closed without merging**
