### PR TITLE
LPS-76604

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
Merged!! Thanks!!

**Comment by daviddotzhang** [comment]
Hey @ealonso
according to my test, this commit is not synced to master yet, could you help to have a look at it ?

**Comment by ealonso** [comment]
Hey @daviddotzhang,

The code is merged on the subrepo, this is merged on master automatically once all tests are in green, please see https://github.com/liferay/liferay-portal/pull/2420.

Regards,
Eudaldo.

**Pull request closed without merging**
