### PR TITLE
LPS-72509 Only validate for concurrent updates based on version (using formDate and lastModifiedDate will not work because Permissions can update Web Content without reloading the form)

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @Alec-Shay

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
Hey @Alec-Shay @jonathanmccann,

I think, this is not the correct fix, because we are generating a regression bug, please check https://issues.liferay.com/browse/LPS-15308, where this code was added.

Regards,
Eudaldo.

**Comment by Alec-Shay** [comment]
Hello @ealonso,

I've looked at this ticket, and noted why it was added, but I'm not quite seeing how this is creating a regression, or what a more correct fix would be.

On my [original notes for this fix here](https://github.com/SamZiemer/com-liferay-journal/pull/10#issue-227831721), I noted that this code will not work as a method of validation whenever the asset (in this case, web content) can be updated without reloading the form. This is meant to prevent concurrent updates, but comparing against the date of the form loading will not work for any forms where this can be done.

Ideally, I might have liked to replace this code with some sort of alternative validation check that would be able to properly catch the types of updates we want to prevent. However, in my testing, this seems to already be caught by [this if-statement here](https://github.com/liferay/com-liferay-journal/blob/master/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L5357), which throws an [ArticleVersionException](https://github.com/liferay/com-liferay-journal/blob/master/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L5365) as well. I actually haven't found a use case (other than the one that is currently broken because of this code) that makes use of this code, because this earlier if-statement seems to catch the relevant cases.

Is there some other validation check that might be more appropriate? I can't seem to think of a better way to do it that could address the problem with the Web Content form.

The only other ways I can think to address this have other issues:

- I considered making it so updating the permissions forces the form to reload, but that could potentially be frustrating for a user when changes are lost
- I also considered just updating the "formDate," but this would not be correct, because it would mean the validation check would just fail to prevent any updates that happen before the Permissions update

What do you think?

**Comment by ealonso** [comment]
Hey @Alec-Shay,

After talking with Julio, we think that the best solution for this scenario is don't allow users modify permission when they are editing the web content. So, if you want to edit the permissions, you should do that using the action "Permissions" in the content list, see screenshot:

web_content_-_community_site_-_liferay

Let me know if I can help you with anything else.

Regards,
Eudaldo.

**Comment by Alec-Shay** [comment]
@ealonso Okay, that makes sense. I'll work on this solution.

Thank you.

**Pull request closed without merging**
