### PR TITLE
LPS-67751 fix journal configuration

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:retest

**Comment by stsquared99** [comment]
ci:retest

**Comment by stsquared99** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retests

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Merged!

**Pull request closed without merging**
