### PR TITLE
LPS-75797 Only update folderId when we are not exporting version history to prevent multiple calls to API

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @rodrigopaulino,

First of all, sorry for the delay, I was waiting for https://issues.liferay.com/browse/LPS-75797, because the solution is more or less the same.

Could you please take a look if this works for you?

Regards,
Eudaldo.

**Comment by rodrigopaulino** [comment]
Hey, @ealonso.

Thank you for looking into this, but I believe this solution will not work for the LPS-75865.
I see that, at [this line](https://github.com/ealonso/com-liferay-journal/blob/5bf234513470cbf4ed66d8185c698611e874b77b/journal-service/src/main/java/com/liferay/journal/exportimport/data/handler/JournalArticleStagedModelDataHandler.java#L846-L847), you call the `updateArticleVersions` method if `exportVersionHistory` is **false** (unmark "Version History"). But even though you're importing the LAR with "Version History" marked, the exported LAR was created with "Version History" unmarked, so there isn't any article version inside that file with its folder already updated. You have to move all the article's versions regardless of what "Version History" option says during the import process.
I hope that helps.
Anything else you might need, don't hesitate to ask.

Regards.

**Comment by pavel-savinov** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pavel-savinov** [comment]
Resent [here](https://github.com/liferay/com-liferay-journal/pull/532)

**Pull request closed without merging**
