### PR TITLE
LPS-75330 Remove usages of AssetUtil - Journal

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
Hey @mtambara,

I was checking the errors in this pull, and there is a test that is broken only in this one: test-subrepository-acceptance-pullrequest-batch(master)/subrepository-integration-mysql56-jdk8

Could you please take a look at it? I don't know if it is related or not, Could you please verify it?

Thanks!!
Eudaldo.

**Comment by mtambara** [comment]
@ealonso Looks like the failure is related, I'll fix it and resend

**Comment by mtambara** [comment]
ci:close

**Pull request closed without merging**
