### PR TITLE
LPS-58672

### PR DESCRIPTION
**Pull request by jpince**
@pavel-savinov @juliocamarero trying again, this time directly to the sub-repo

### CODE REVIEW

**Comment by pavel-savinov** [comment]
Thanks @jpince! There was a typo...

**Comment by pavel-savinov** [comment]
ci:stop

**Comment by jpince** [comment]
cc/ @hhuijser @juliocamarero @jhendley @jrhoun
https://github.com/brianchandotcom/liferay-portal/pull/42921
https://github.com/pavel-savinov/liferay-portal/pull/30

**Comment by jpince** [comment]
@pavel-savinov please allow the PR Tester to run, I'd like to see it finish successfully on this sub-repo pull.
ci:retest

**Comment by jpince** [comment]
@pavel-savinov @juliocamarero QA Engineering is saying that there is no way to push this to central, as the SF error will still persist in that pull, so ci merge will not work. They are going to ask Sam to look into this today.

**Comment by jpince** [comment]
@pavel-savinov @juliocamarero note the 2nd commit I added, this was not revealed until after the first was resolved.

@michaelhashimoto has the PR Tester set up for his fork of the journal sub-repo, those two commits passed the compile/semver/PMD/SF/unit tests there https://github.com/michaelhashimoto/com-liferay-journal/pull/5#issuecomment-245065976

cc/ @jhendley @jrhoun @anthony-chu

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Merged! Thank you! 👍

**Pull request closed without merging**
