### PR TITLE
LPS-66646

### PR DESCRIPTION
**Pull request by kenjiheigel**
@juliocamarero, please merge this as soon as you can after https://github.com/brianchandotcom/liferay-portal/pull/44846 has been merged, so we can turn the poshi web content tests back on.

cc-ing: @anthony-chu

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by anthony-chu** [comment]
@juliocamarero `PGWebcontentdisplay#SelectWebContent` failure is an expected failure due to the rename.

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
The central pull has been merged:
https://github.com/brianchandotcom/liferay-portal/pull/44846

The previously failing functional test should pass now, since the changes are in.

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Merged! 👍

**Comment by kenjiheigel** [comment]
@juliocamarero thanks! I sent a pull to reenable the PR tester tests:
https://github.com/brianchandotcom/liferay-portal/pull/44932

**Pull request closed without merging**
