### PR TITLE
LPS-71788 No log needed for checking WCM in DL

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by anthony-chu** [comment]
@achaparro @ealonso There's currently an issue with the NPM mirror that is causing all master pulls to fail when building the dynamic-data-mapping module (please see relevant Loop post [here](https://loop.liferay.com/home/-/loop/feed/4805929)). Sorry for the inconvenience.

**Comment by anthony-chu** [comment]
ci:retest

**Comment by ealonso** [comment]
Merged!!! Thanks!!!

**Pull request closed without merging**
