### PR TITLE
LPS-72895 Changing article view permissions check does not clear cache allowing guests to still view articles

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
@ealonso It looks like version 2.1.0 of "com.liferay.portal.configuration.persistence" hasn't been published yet and version 2.0.6 doesn't have the classes necessary. Any thoughts on how to handle the situation?

**Comment by ealonso** [comment]
Hey @jonathanmccann,

I think the only way to handle this situation is publishing a new version, so, Could you talk with @brianchandotcom to publish a new version of that module? or a snapshot?

Regards,
Eudaldo.

**Comment by jonathanmccann** [comment]
@ealonso 

Thanks for the reply. Before making Brian publish that module, would you mind letting me know if this change would be accepted or not? I don't want to have him go through the trouble if the fix is going to be completely different.

Thanks!

**Comment by jonathanmccann** [comment]
@ealonso Any update on whether or not this fix would be accepted before having Brian publish the module?

**Comment by ealonso** [comment]
Hey @jonathanmccann,

I think @jkappler added some comments to [LPS](https://issues.liferay.com/browse/LPS-72895) ticket, Could you please take a look at it?

Regards,
Eudaldo.

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Hi @jonathanmccann, we'll go ahead with the fix as mentioned in jira.

Thanks for everything.

cc:// @ealonso

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by jonathanmccann** [comment]
@ealonso @jkappler Looks like we're good to go. Let me know if you need anything else from me.

**Pull request merged**
