### PR TITLE
LPS-76631 Template Context contributors do not work in Web Content templates

### PR DESCRIPTION
**Pull request by IstvanD**
Hello,

Could you please review this pull request?

Thank you,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test

**Comment by IstvanD** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
Hey @IstvanD,

I took your old solution in https://github.com/liferay/com-liferay-journal/pull/583 and I solved the tests to prevent null pointer exceptions, please see, https://github.com/liferay/com-liferay-journal/pull/593. 

I'm going to merge https://github.com/liferay/com-liferay-journal/pull/593 once all the tests pass.

Regards,
Eudaldo.

**Comment by IstvanD** [comment]
Hey @ealonso 

OK, thanks for the information.

Best regards,
István

**Pull request closed without merging**
