### PR TITLE
LPS-70435 Index article Id as sortable field

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
Hey @brianchandotcom @stsquared99,

Do you know if this error is related with my code or not? I cannot find the problem.

Thanks!!!,
Eudaldo.

**Comment by stsquared99** [comment]
@pyoo47 @michaelhashimoto Can you guys take a look?

**Comment by pyoo47** [comment]
@ealonso The error here is being caused by an issue with testReport publishing. We are going to do a rebuild tonight that will fix this problem.

**Comment by ealonso** [comment]
ci:retest

**Pull request merged**
