### PR TITLE
LPS-68581 Ignoring inline height to keep the ratio.

### PR DESCRIPTION
**Pull request by zxdgoal**

### CODE REVIEW

**Comment by zxdgoal** [comment]
ci:retest

**Comment by zxdgoal** [comment]
ci:retest

**Comment by zxdgoal** [comment]
ci:retest

**Comment by ealonso** [comment]
Please see: https://github.com/jbalsas/liferay-portal/pull/623#issuecomment-256608667

**Comment by ealonso** [comment]
https://issues.liferay.com/browse/LPS-68581

**Pull request closed without merging**
