### PR TITLE
 LPS-67885 Partially revert LPS-53479 so older versions can be expire…

### PR DESCRIPTION
**Pull request by juangon**
…d. Actual fix had been committed under LPS-63908

### CODE REVIEW

**Comment by juangon** [comment]
@hhuijser why is giving this source formatting error? when executing in my local env. it is successfull and doesn't change any file.

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
ci:retest

**Comment by pyoo47** [comment]
@juangon 
Replace liferay-portal/modules/apps/web-experience/journal with your journal subrepo contents and then from within that directory execute “../../../../gradlew formatSource”. I did that and sourceFormatter found a lot of changes. Here’s the output that I got when running against latest from the journal subrepo. https://gist.github.com/pyoo47/28b71a1e4935ee7d27d26058a932beef

**Comment by hhuijser** [comment]
Hey @juangon, sorry for the late response. I was on leave and missed your comment.
There were a bunch of checks that were not working properly outside of portal.
Should be working properly now.

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
Thanks very much @hhuijser seems now it passed! @juliocamarero seems ready to review...

**Comment by hhuijser** [comment]
Glad it's passing now... sorry for all the inconvenience...

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juangon** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
@juangon parece que hay 1 test que se rompe con tus cambios: 
JournalFolderLocalServiceTest.testGetNoAssetFolders

podrías echarle un ojo?

gracias!

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
hey @juliocamarero, this error isn't related to my pull (it happened to others like https://github.com/liferay/com-liferay-journal/pull/12#issuecomment-249594129).

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
ci:retest

**Comment by juangon** [comment]
@juliocamarero @ealonso all tests passes, it's ready for review at last!

**Comment by juangon** [comment]
Seems this had been committed without updating this pull. So it can be closed @juliocamarero @ealonso

**Comment by juliocamarero** [comment]
merged 👍 

thank you!

**Pull request closed without merging**
