### PR TITLE
LPS-71181

### PR DESCRIPTION
**Pull request by jonathanmccann**
Related to https://github.com/ealonso/liferay-portal/pull/855

/cc @JonathanAichler

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @carloslancha,

Could you please review this one?

Thanks!!!

**Comment by ealonso** [comment]
ci:retest

**Comment by anthony-chu** [comment]
@JonathanAichler @jonathanmccann @SamZiemer @ealonso

There's a javascript error that's thrown when editing the article:
```
TypeError: a.after(...) is not a function
```

Then, when trying to add content into the AlloyEditor content field, another TypeError is thrown:
```
TypeError: Liferay.form.get(...) is undefined
```

**Comment by ealonso** [comment]
Hey @JonathanAichler @jonathanmccann @SamZiemer,

Could you please fix the js error and resend?

Thanks!!!!

**Comment by jonathanmccann** [comment]
It's probably because the portal fix has not yet been merged - https://github.com/ealonso/liferay-portal/pull/855

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
See https://github.com/liferay/com-liferay-journal/pull/236

**Pull request closed without merging**
