### PR TITLE
LPS-72906 Article display stays cached even if update on template gets done

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @Preston-Crary @shuyangzhou,

Could you please take a look at it?, I'm not sure if it can affect to performance.

Regards,
Eudaldo.

**Comment by Preston-Crary** [comment]
@ealonso,

I'll try to take a look at it today.

**Comment by Preston-Crary** [comment]
Sorry, I wasn't able to finish this today.  I did start looking at it and should have a pull ready tomorrow.

**Comment by ealonso** [comment]
Hey @Preston-Crary,

Thanks you very much for your help, we really appreciate it.

Regards,
Eudaldo.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/com-liferay-journal/pull/39

**Comment by Preston-Crary** [comment]
ci:close

**Pull request closed without merging**
