### PR TITLE
LPS-74522 Able to create Web Content with same ID if the article is in a different folder with different version

### PR DESCRIPTION
**Pull request by rimisaadouwork**
Hi,

Could you please review this commit.
https://issues.liferay.com/browse/LPS-74522
I modified the logic to handle import export (staging). See old commit:
https://github.com/liferay/com-liferay-journal/pull/458

Thanks,

### CODE REVIEW

**Comment by rimisaadouwork** [comment]
ci:retest

**Comment by ealonso** [comment]
Hey @rimisaadouwork,

I don't like the idea of having an attribute in servicecontext to do that, is there any other way?

Regards,
Eudaldo.

**Comment by rimisaadouwork** [comment]
Hi @ealonso,
I already discussed the solution with @moltam89 but we concluded that this is the best and only way to do it.
If you have a better idea please feel free to share it with us.

**Comment by ealonso** [comment]
Hey @rimisaadouwork,
Could you please scale the issue?
Regards,
Eudaldo.

**Comment by rimisaadouwork** [comment]
Hi @ealonso,
What do you mean?
Thanks,

**Comment by ealonso** [comment]
@rimisaadouwork 

Update the LPS ticket to scale to the Team, so then we can work on it and try to find a solution

**Comment by rimisaadouwork** [comment]
Do you mean to scale the Priority?
Because I never heard about scaling.
Thanks,

**Comment by ealonso** [comment]
I think now it is called "Expedite"

**Comment by ealonso** [comment]
@rimisaadouwork This makes sense for you now?

**Comment by dacousalr** [comment]
Don't worry @rimisaadouwork,

I will escalate this ticket to @ealonso's Team.

Thanks

**Pull request closed without merging**
