### PR TITLE
LPS-69630

### PR DESCRIPTION
**Pull request by jonathanmccann**
@juliocamarero Let me know if you're accepting pulls to this repository or if you still want them merged in to ee-7.0.x first. Thanks!

/cc @mtambara

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hey @jonathanmccann 

we are accepting pulls now. We are not as fast as portal, but we do our best :)

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jonathanmccann** [comment]
Great, thanks for letting me know!

**Comment by juliocamarero** [comment]
Merged! thanks! 👍

**Pull request closed without merging**
