### PR TITLE
LPS-72670 Use search engine snippets for highlighting

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by BryanEngler** [comment]
depends on https://github.com/mhan810/liferay-portal/pull/1346

**Comment by BryanEngler** [comment]
Hey @ealonso, I havent sent very many prs to this repo so I was just wondering, if prs for this repo depend on portal commits, do these prs usually get merged after the portal prs are merged?

**Comment by ealonso** [comment]
Hey @BryanEngler,

Yes, If it depends on a portal pull, we merged it after the portal pull is merged. Also, we only merge the pull if all the test are in green.

In this case some tests are broken, I image it is because the portal pull is not merge yet, so, Could you please add a "ci:retest" comment when the portal pull is merged?

Regards,
Eudaldo.

**Comment by BryanEngler** [comment]
ya sounds good, thanks!

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
see: https://github.com/liferay/com-liferay-journal/pull/408

**Pull request closed without merging**
