### PR TITLE
LPS-75787

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @mbowerman @matethurzo

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by mbowerman** [comment]
Test failures due to [LPS-76573](https://issues.liferay.com/browse/LPS-76573), unrelated to this pull

**Comment by ealonso** [comment]
ci:test

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Merged, thank you

**Pull request closed without merging**
