### PR TITLE
LPS-66831 As a Roles Admin user, I would like to see the number of assignees for each role in the role search results

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-66831](https://issues.liferay.com/browse/LPS-66831).

Hey @juliocamarero, I'm not sure what the proper workflow for this is, but this is a change I originally included in https://github.com/brianchandotcom/liferay-portal/pull/43415.  Let me know if there's anything else I need to do.  Thanks!

/cc @brianchandotcom

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hey @drewbrokke!

as part of the subrepo, I think we can't reference default versions anymore. We need to reference published jars of snapshots. Why do you need journal to depend on the latest portal-kernel? are you adding any new method that we will use later? (I didn't see any change in your pull that affected journal..)

I think that the workflow would be:
1) modify portal-kernel and ask Brian to publish a snapshot
2) send us a pull to use the latests snapshot so that we can use the new methods

does this make sense to you? I am confused why you need us to update the journal dependency though ...

**Comment by drewbrokke** [comment]
Hey Julio, I made the update to journal-api because the new minor version bump of the portal.kernel.model package (to 1.1.0) was causing a deploy-time failure (since the current expectaiton is any version up to but not including 1.1.0).  This was the case with nearly all of the api packages.  From what I could tell, an update to both the build.gradle and bnd.bnd for each affected module was necessary.

I'm happy to have Brian publish a snapshot as long as there is a way for him to publish that change without updating your module and still have the build pass. That's the part that's not totally clear to me.

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by drewbrokke** [comment]
Sorry I forgot to close this.  We're working on a solution that should make these changes unnecessary.  Thanks @juliocamarero!

**Pull request closed without merging**
