### PR TITLE
LPS-67339 Update xsd files

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
Merged! Thanks! 👍

**Pull request closed without merging**
