### PR TITLE
LPS-70494 Optionally fetch latest journal articles without pagination…

### PR DESCRIPTION
**Pull request by mtambara**
… to hit the finder cache

### CODE REVIEW

**Comment by mtambara** [comment]
ci:retest

**Comment by ealonso** [comment]
Hey @mtambara,

I have some question regarding your pull request:

1. Why we need a property on user interface to get the latest article without pagination?
2. What is the real problem that we are trying to resolve? Can I test it? and why we need this code only in journal and only in that method?

I was checking the https://issues.liferay.com/browse/LPS-70494 and it was closed, It seems to be fixed on master? or we should reopen it?

Regards,
Eudaldo

**Comment by mtambara** [comment]
@ealonso This change stemmed from https://issues.liferay.com/browse/LPP-24212. Basically, whenever we add a JournalArticle we clear the paginated finder cache, so when we do a paginated fetch immediately after, we always need to actually hit the db. Doing a non-paginated fetch and sorting in memory hits the cache and avoids costly db access.

**Comment by brianchandotcom** [comment]
@mtambara 

See https://github.com/liferay/liferay-portal/commit/0614fa3a1271d9d729a9f1f1e9f5ddcac6d7e506

I had to make that change because of an error in https://gist.github.com/brianchiu/562cd8fc8aed454ae89cbf2706f78a84

after publishing journal-service in 7.0.x.

The root issue is that we're bumping up the package com.liferay.journal.configuration because there are methods in 7.0.x that are not in master.

But I compared this pull with what is in 7.0.x, and it still has missing methods. Our goal is to not bump up packages (and deprecate where possible).

Can you come grab me tomorrow to make this pull cleaner? 


Thx.

fyi @ealonso

**Comment by ealonso** [comment]
Thansk @brianchandotcom @mtambara, closing it for now.

**Pull request closed without merging**
