### PR TITLE
LPS-74522 Able to create Web Content with same ID if the article is in a different folder with different version

### PR DESCRIPTION
**Pull request by rimisaadouwork**
Hi,

Could you please review this commit.
https://issues.liferay.com/browse/LPS-74522

Thanks,

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
Merged!! Thanks!!

**Comment by ealonso** [comment]
Hey @rimisaadouwork,

This pull broke some tests, Could you please take a look at it?

Regards,
Eudaldo.

**Comment by rimisaadouwork** [comment]
Hi @ealonso,
I will reopen the LPS because it seems that the fix create regressions and we don't know how to solve the issue in a right way.

Thanks,

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dacousalr** [comment]
ci:retest

**Pull request closed without merging**
