### PR TITLE
[Technical-Support] LPS-75797

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @yuhai,

What happen if you modify the expiration date when it is not null?

1. Create a Web Content without Expiration Date
2. Publish to Staging
3. Update Web Content with a new Expiration Date
4. Publish to Staging
5. Update Web Content with a new Expiration Date
6. Publish to Staing

Expected Result:
The expiration date is the same for all Web Content

Actual Result:
The expiration date is the same for version 1.0 and 1.1 but is different for 1.2

After looking at the code, this bug was introduced in: https://issues.liferay.com/browse/LPS-58438, in this LPS we ignore the expiration date update when we are doing a export/import process.

Regards,
Eudaldo.

**Comment by yuhai** [comment]
Hi @ealonso,

From my understanding, the step "Publish to Staging" means "publish to live". If so, I think explain the behavior:

1. In staging site, create a Web Content without Expiration Date
2. Publish to live, by default, checked "export history versions"
3. Update Web Content with a new Expiration Date
4. Publish to live, by default, checked "export history versions"
5. Update Web Content with a new Expiration Date
6. Publish to live, by default, checked "export history versions"

Expected Result and Actual Result are same:
The expiration date is the same for all Web Content version, because when update one web content with Expiration Date, it will update the all old versions with same expiration date. That is to say, in staging site, all versions of the web content own Expiration Date. After publish to live, in live site, all versions of the web content also own Expiration Date.

However, the issue is "publish to live without checking export history versions". If based on the above steps, in live site, web content (version:1.0) won't have Expiration Date because LPS-58438 (https://github.com/ealonso/liferay-portal-ee/commit/669c80afce65e2feca7c1ed618f0d3a10db92d31) ignored the expiration date update (for old versions) when we are doing a import process. The commit explicitly added the check "block update history versions when the latest version with Expiration Date in the import progress".

Please check the fix detailed explanation from https://github.com/hhuijser/com-liferay-journal/pull/15#issue-272861155

Regards,
Hai

**Comment by ealonso** [comment]
Hey @yuhai,

When I said "Publish to Staging" it means "publish to live", also It suppose to have "export history versions" unchecked, like in the LPS-75797.

Regards,
Eudaldo

**Comment by yuhai** [comment]
Hi @ealonso 

Thanks for your clarification.

Based on the case with "export history versions" unchecked, all the versions of web content should have different Expiration Date in live site.

> 1.Create a Web Content without Expiration Date
> 2.Publish to Staging
> 3.Update Web Content with a new Expiration Date
> 4.Publish to Staging
> 5.Update Web Content with a new Expiration Date
> 6.Publish to Staging

Actual Result:
The expiration date is different for version 1.0 and 1.1 and 1.2 in live site.

version:1.0, Expiration Date:null.
version:1.1, Expiration Date: same as step3.(for example, 2017-11-15)
version:1.2 Expiration Date: same as step5. (for example, 2017-11-17)

However, in staging site, the expiration date is the same for all Web Content.

version:1.0, Expiration Date: same as step5.(for example, 2017-11-17)
version:1.1, Expiration Date: same as step5.(for example, 2017-11-17)
version:1.2 Expiration Date: same as step5. (for example, 2017-11-17)

The fix was based on the commit (https://github.com/ealonso/liferay-portal-ee/commit/669c80afce65e2feca7c1ed618f0d3a10db92d31) was right. If we remove it, the issue LPS-75797 will be fixed.

Regards,
Hai

**Comment by jorgediaz-lr** [comment]
Hi @yuhai @ealonso 

I am worry about simply removing https://github.com/ealonso/liferay-portal-ee/commit/669c80afce65e2feca7c1ed618f0d3a10db92d31 , we can cause throughput problems during publish to Live or LAR import.

If you publish only the last version of a webcontent with a expiration date set, all is ok, you have 100*1 updates (old versions)   :thumbsup:
But, If you publish a webcontent with all the history, for example 100 wc, with its expiration date set, you will have 100 updates for each 100 versions: 100*100   :thumbsdown:

So we should be careful with that, perhaps we should do it only in case of not publishing the full history of webcontents. (we can check that in JournalArticle staging data handler)

**Comment by jorgediaz-lr** [comment]
Hi @yuhai 

I have spoken this morning with @ealonso , after explaining the whole issue we have decided that the correct solution is to do the change in  JournalArticle staging data handler.

If "export history versions" is set to true, we don't have to do anything because we are already publishing all versions with the correct expired date. 👍 

In case of having "export history versions" to false and expired date != null, we have to update all versions in Live with the new expired date. 

Inside of `JournalArticleStagedModelDataHandler.doImportStagedModel` after importing the JournalArticle:

1. Check "export history versions" is false:  `portletDataContext.getBooleanParameter(NAMESPACE, "version-history")` = false
2. If "export history versions" is false, check `isExpireAllArticleVersions` = true (see following code https://github.com/liferay/com-liferay-journal/blob/0c6d3db3042a36b1d03d34dfad27892d88770d37/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L7548-L7556 ) 
3. If both "export history versions" is false and `isExpireAllArticleVersions` = true and expiration date is not null, set the article expiration date to all old versions.

In order to avoid issues with transactions, in my opinion we should do it in the same thread: We have to do the same setArticlesExpirationDate functionality, but **without the callback:** https://github.com/liferay/com-liferay-journal/blob/0c6d3db3042a36b1d03d34dfad27892d88770d37/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L7987-L8018

@ealonso please review this solution and tell us any additional idea about it

/cc: @samanzanedo

**Comment by ealonso** [comment]
Hey @yuhai,

please see @jorgediaz-lr comments and resend

Thanks!!
Eudaldo.

**Comment by yuhai** [comment]
Hi @jorgediaz-lr  and @ealonso 

Thanks for your detailed explanation.

Sorry for the delayed response. I was not in the office on last Friday. I just submit the new PR to review. 
https://github.com/hhuijser/com-liferay-journal/pull/16

Regards,
Hai

**Pull request closed without merging**
