### PR TITLE
LPS-76631 Template Context contributors do not work in Web Content te…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…mplates

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
Hey @IstvanD,

This pull break some integration tests, Could you please take a look at it?

Regards,
Eudaldo.

**Comment by IstvanD** [comment]
Hey @ealonso 

I'm sorry, I'll resend a pull request with the corrected solution.

You can close this pull.

Greetings,
István

**Pull request closed without merging**
