### PR TITLE
LPS-67687 Liferay not searching correctly in Japanese even though proper tuning is performed

### PR DESCRIPTION
**Pull request by arboliveira**
Hi @juliocamarero,

This is a fix to cease indexing the plain `title` field into the `Document` assembled by `JournalArticleIndexer`. It does solve the scenario reported in this ticket, but your second opinion would be extremely welcome.

https://issues.liferay.com/browse/LPS-67687

The root cause, as far as we could diagnose, is that the `title` field is mapped to the default Elasticsearch analyzer - therefore English. So whenever we have a site with Japanese as default locale, titles written in Japanese get indexed into the English analyzed `title` field generating incorrect tokens; later on when searched, these tokens match a lot more documents than they should. As @jordirodo put it, it's like it's matching by individual letters (kanji characters) instead of full words and word prefixes. Here you can find his extensive investigation, including lots of examples for broken searches on Japanese web content titles, and valuable insights from @lipusz:

https://in.liferay.com/web/support/forums/-/message_boards/view_message/25120917#_19_message_25117650

I used the examples above as basis for the integration tests included in this pull request. They go red without the fix (too many documents found) and green when the fix is applied. (just the right documents found.)

https://github.com/arboliveira/com-liferay-journal/blob/27d840aedb67fdb8fa5d67eeb6b75cd7d0d25d07/journal-test/src/testIntegration/java/com/liferay/journal/search/test/JournalArticleIndexerLocalizedContentTest.java

I also wrote a few 5-second unit tests (in `portal-search-elasticsearch`) to illustrate correct analysis and search when the `kuromoji` analyzer is used - that's the one we already map to `localized_title_ja*`:

https://github.com/arboliveira/liferay-portal/blob/bd1ba18314782694850246f6be718c534802a348/modules/apps/foundation/portal-search/portal-search-elasticsearch/src/test/java/com/liferay/portal/search/elasticsearch/internal/index/LiferayTypeMappingsJapaneseTest.java

https://github.com/arboliveira/liferay-portal/blob/bd1ba18314782694850246f6be718c534802a348/modules/apps/foundation/portal-search/portal-search-elasticsearch/src/test/java/com/liferay/portal/search/elasticsearch/internal/index/LiferayTypeMappingsPrefixPerLanguageTest.java

And this is the fix:

https://github.com/arboliveira/com-liferay-journal/commit/14456a6096b0ce98efbee6fe7684ecc32f864bbd

The fix works because the `title` field is out of the picture, but `title_ja*` and `localized_title_ja*` still participate in the query - they're mapped to the `kuromoji` analyzer and Japanese tokens are parsed correctly at both indexing and search time, so only relevant documents are matched.

(We will probably have similar fixes for other localizable fields like `content` and `description` - and a different, "single translation" approach for non localizable fields that can still receive content in virtually any language, like DL and Bookmark titles.)

I ran all Search related integration tests in our codebase and nothing broke. As far as we can rely on our test coverage, if the CI PR tester finds nothing else we should be safe.

https://github.com/arboliveira/liferay-search-tck/blob/b24d7d34e91db52e013b14da84f0f6215b45b487/test/integration/com/liferay/portal/search/tck/AllSearchTestsArquillian.java#L28-L44

https://github.com/arboliveira/liferay-search-tck/blob/b24d7d34e91db52e013b14da84f0f6215b45b487/test/integration/com/liferay/portal/search/tck/AllSearchTests.java#L26-L40

Please review and let us know of any concerns you can think of.

Thank you!!

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
merged! 👍

**Comment by arboliveira** [comment]
Became https://github.com/liferay/com-liferay-journal/pull/49

**Pull request closed without merging**
