### PR TITLE
LPS-76631 Template Context contributors do not work in Web Content templates

### PR DESCRIPTION
**Pull request by IstvanD**
Hello,

I created a simplified version of https://github.com/liferay/com-liferay-journal/pull/560 that checks if the request exists as it may not during the rendering phase.

Best regards,
István

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @IstvanD,

Could you please send this one to @shuyangzhou? To have a second opinion about the performance.

Regards,
Eudaldo.

**Comment by IstvanD** [comment]
Hey @ealonso 

I have sent the pull request https://github.com/shuyangzhou/com-liferay-journal/pull/64 to @shuyangzhou 

Best regards,
István

**Comment by IstvanD** [comment]
The performance tests were run
https://github.com/shuyangzhou/com-liferay-journal/pull/64#issuecomment-354938018

**Comment by IstvanD** [comment]
Hey @ealonso 

In light of the performance test results, do you find the solution feasible?

Thank you and best regards,
István

**Pull request closed without merging**
