### PR TITLE
LPS-X Defer JournalArticleAssetRenderer's JournalServiceConfiguration…

### PR DESCRIPTION
**Pull request by shuyangzhou**
… creation

### CODE REVIEW

**Comment by ealonso** [comment]
Resend with and LPS number LPS-71556

**Comment by shuyangzhou** [comment]
Sorry, I meant to send this to myself for ci test. But it is a good change, thanks for creating a ticket for it @ealonso !

**Comment by ealonso** [comment]
Hey @shuyangzhou,

The semantic versioning are related with your changes? I was trying to find the problem but I cannot not found the root issue, because in my local machine everything is working fine.

**Comment by shuyangzhou** [comment]
No, it is not related here. I fixed it already in https://github.com/liferay/com-liferay-journal/commit/455ceb31b940941995ebb4074c59c0c170236d5d

QA supposed to apply a change to CI to remove all version override files, and I was told they did it yesterday, somehow it is still happening here, I will check with @michaelhashimoto today. But this pull is fine, that's a known issue, and it has been fixed, at least at code level, just the way how CI is running this is broken.

**Comment by ealonso** [comment]
Hey @shuyangzhou,

Thanks for the explanation.

**Pull request closed without merging**
