### PR TITLE
LPS-76056 Deals properly with TranslationManager asynchronous registration

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:retest

**Comment by anthony-chu** [comment]
hi @jbalsas @ealonso, it looks like there's a javascript error that's thrown when the user is brought to the edit screen for web content:

`JAVA_SCRIPT_ERROR: ReferenceError: STR_TRANSLATION_MANAGER is not defined`

this is causing our journal acceptance tests to fail.

**Comment by jbalsas** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:retest

**Comment by ealonso** [comment]
Merged!! Thanks!!

**Pull request closed without merging**
