### PR TITLE
LPS-70627 Sets publishDate on updateAsset method

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by rimisaadouwork** [comment]
Hi @ealonso,

I 'm confused by your code:
publishDate = article.getDisplayDate();

Is the article display date the publish date when you copy an article? I need to understand why you did that. 

Thanks!

**Comment by ealonso** [comment]
Hey @rimisaadouwork,

For journal article de publish date is the display date.

Regards,
Eudaldo.

**Comment by rimisaadouwork** [comment]
Hi @ealonso,

Thank you for your answer.
I have a question regarding back porting this issue to ee-6.2.x and DXP.

What do I need to do if I want to back port this fix to ee-6.2.x?
And how about DXP?

Thanks!

**Comment by ealonso** [comment]
Hey @rimisaadouwork,

I think, you should do it like with other LPS. The commits was merged on master here: https://github.com/liferay/liferay-portal/pull/1259, so I think you don't need to do nothing special.

Regards,
Eudaldo

**Comment by rimisaadouwork** [comment]
Hi @ealonso,

For example do I need to add the fix to liferay-portal-ee (ee-6.2.x) branch or to com-liferay-journal (ee-6.2.x I don't see it)?

And how about ee-7.0.x? Do i need to add the fix to com-liferay-journal ee-7.0.x branch (I only see 7.0.x)?

Thanks !

**Comment by ealonso** [comment]
Hey @rimisaadouwork,

We only have the journal repo for master, for ee-7.0.x and ee-6.2.x we don't have it.

Regards,
Eudaldo.

**Pull request merged**
