### PR TITLE
LPS-67407 SF - compliance with new rules

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LPS-67407

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
