### PR TITLE
LPS-72509 Do not allow updates to Permissions while editing Journal content (updating while form is loaded interferes with a validation check for concurrent updates)

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @shuyangzhou @brianchandotcom @hhuijser 

We are facing the following source formatter error:

`
Use portal service reference instead of 'com.liferay.portal.kernel.util.HttpUtil' in modules, see LPS-69661: ./src/main/java/com/liferay/journal/internal/util/JournalConverterImpl.java
`

We get this error only on CI and not in our local machines, also if you look at the error, it is saying we need to use portal service for 'com.liferay.portal.kernel.util.HttpUtil'. Do you know if we need to update something?. Because looking at LPS-69661, it seems to be only for PortalUtil not for HttpUtil.

Regards,
Eudaldo.

**Comment by shuyangzhou** [comment]
@ealonso it needs to be changed to use
```
@Reference
private Http _http;
```

We are applying it system wide, there will be more *Util added to the list.

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:retest

**Comment by hhuijser** [comment]
Hey @ealonso 

We have a number of checks that can potentially fail on CI while it passes SF when you run it locally.

The reason is that when it's tested on CI, the journal subrepo is first moved to 'liferay-portal/modules/apps'.
Since SF does some cross reference checks (missing language keys is an example), SF will be able to do those checks when executed on CI, but when you run SF locally from the subrepo, you do not have access to portal and it cannot do those checks.

I have discussed this with @juliocamarero. I don't think there is an easy solution. Maybe we can somehow have an option to specify where the portal is sitting and use that location to do cross reference checks when running locally, but that gets pretty hacky.

Hope my explanation makes sense. If not, ask Julio :)

**Comment by ealonso** [comment]
@shuyangzhou @hhuijser 

Thanks!!!

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by ealonso** [comment]
https://github.com/liferay/com-liferay-journal/pull/335

**Pull request closed without merging**
