### PR TITLE
LPS-75284 Edit an article on title click instead of preview in accordance with new lexicon pattern

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@anthony-chu Could you please check if we have a POSHI test for this? This change is in accordance with new Lexicon pattern so I guess we should change the POSHI also.
Thanks!

**Comment by anthony-chu** [comment]
hi @pavel-savinov, we have tests that edit a web content article by selecting "Edit" in the kebab menu. we can add a test that makes sure we edit by clicking the article title as well.

**Comment by ealonso** [comment]
Hey @pavel-savinov,

We need to apply this change to view history, feeds, search ...

Could you please talk with @beatrizma about it?

Regards,
Eudaldo.

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
