### PR TITLE
LPS-76631 Template Context contributors do not work in Web Content templates

### PR DESCRIPTION
**Pull request by IstvanD**
Hello,

Could you please review this pull request?

Please find the issue description and the explanation of the fix in the LPS
https://issues.liferay.com/browse/LPS-76631

Thank you and best regards,
István

### CODE REVIEW

**Comment by epgarcia** [comment]
Hi @IstvanD 

Thanks for the PR. I remember having discussed with @rotty3000 and/or @shuyangzhou @tinatian about the convenience of using templateContextHelper's prepare in Journal templates. AFAIR, it was a matter of performance and exposing certain variables we didn't want in this type of templates. Maybe they can provide more details. 

Thanks

**Comment by IstvanD** [comment]
Hi @epgarcia 

Thanks for the info!
Dear @rotty3000, @shuyangzhou, @tinatian could you please share your thoughts and/or concerns about using such variables in Web Content templates, so I can share these insights with the customer, eg. offer alternatives to them?

Thank you in advance!

Best regards,
István

**Comment by rotty3000** [comment]
... because the request value of ThemeDisplay did not exist during the
rendering phase of web contents!

It may now.. but it did not then.

The render phase of web content happens at the Local service layer, which
may be invoked without any servlet request.

**Comment by IstvanD** [comment]
Hello,

I created a version that checks for the existence of the reqiest
https://github.com/liferay/com-liferay-journal/pull/568

Best regards,
István

**Pull request closed without merging**
