### PR TITLE
LPS-67407 SF - compliance with new rules

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juliocamarero** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Pull request closed without merging**
