### PR TITLE
LPS-68297

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/43351

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by juangon** [comment]
@hhuijser @juliocamarero I am having same validation error. Are these errors be fixed with liferay-portal pull and this one?

**Comment by juliocamarero** [comment]
hopefully :)

**Pull request merged**
