### PR TITLE
Lps 71850

### PR DESCRIPTION
**Pull request by shuyangzhou**
@pavel-savinov I fixed many things in your pull, please take a look. I hope next pull from you would be at this strength. But this code is still buggy, I am letting it go as it has been deferring for too long, but it does not make it right. Currently it does not take account when cutting happens in the middle of a tag. For example:
`JournalStringUtil.shortenWithHtml("<a></a>", 5)` outputs `<a></</a>...`, while I believe normally people would expect just `<a></a>` with no change. If you want to continue on this, feel free to send me a follow up pull after this is merged.

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @shuyangzhou,

Thanks you very much for your help. For the moment, we are going to use this approach https://github.com/liferay/com-liferay-journal/pull/434, and @pavel-savinov is going to continues working on fixing those bugs, https://github.com/pavel-savinov/com-liferay-journal/pull/2.

Regards,
Eudaldo.

**Comment by shuyangzhou** [comment]
@ealonso HtmlUtil.stripHtml() is a very heavy process, which may cause large performance regression.

@slnn please check on this for our journal test.

Even though this is just a temp state, if it affects our day tests too much, we still can not afford it, as it will shade away other regressions.

**Comment by slnn** [comment]
Here are test results for this pull on Journal test :

Portal Version | Session Count | Mean Time of Login | Mean Time of View Page
------------ | ------------- | ------------- | -------------
BaseLine | 32583 | 531| 194
PR | 31983| 493| 180

**Comment by shuyangzhou** [comment]
OK, that is within acceptable range. @slnn can you double check whether our test case even touch the changed lines?

**Comment by slnn** [comment]
OK got it

**Comment by slnn** [comment]
Hi Shuyang,

Our test case of Journal did not touch the changed lines, but test case of Asset Publisher would touch the change lines.

I am running Asset Publisher test for this pull to check performance.

_**JournalArticleDescriptionEditorConfigContributor.populateConfigJSONObject()**_ would be invoked when add a basic web content,
_**JournalStringUtil.shortenWithHtml()**_ would be invoked when visit the Asset Publisher portlet that contained basic web content.

**Comment by slnn** [comment]
Here are test results for this pull on Asset Publisher test :

Portal Version | Session Count | Mean Time of Login | Mean Time of View Page With Filter
------------ | ------------- | ------------- | -------------
BaseLine | 11016 | 574| 308
PR | 10812| 578| 321

**Comment by shuyangzhou** [comment]
OK, still within 2%, no big deal then, we can just keep it like this for now, thanks @slnn !

**Pull request closed without merging**
