### PR TITLE
LPS-76339 Wrong redirect after clicking on notification about journal article with display page

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
Hey @anthony-chu,

Do you know why those WebContentUpgrade tests are broken? I was checking those errors and I couldn't find the error. Could you please help me?

Thanks!!,
Eudaldo

**Comment by anthony-chu** [comment]
Hi @ealonso! I'm sorry, I missed this message. I took a look at it today, and it looks like there is a regression with publishing draft articles after upgrading. I've filed it here: [LPS-76831](https://issues.liferay.com/browse/LPS-76831).

**Comment by ealonso** [comment]
Hey @anthony-chu,
Don't worry, and thanks you very much for the information and the ticket.

**Pull request merged**
