### PR TITLE
LPS-76339 Wrong redirect after clicking on notification about journal article with display page

### PR DESCRIPTION
**Pull request by IstvanD**
Hello,

Could you please review this pull request?

Thank you,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Dear Reviewer,

Could you please take a look at this pull request?
The customer ticket the issue is reported on is not yet resolved.

Thank you in advance!

Best regards,
István

**Comment by ealonso** [comment]
Hey @IstvanD,

After reviewing the behavoiur it seems to be the same for all assets, when you click in the link, you are redirected to the portlet in the control panel. Then, if we change this behaviour for journal we are creating an inconsistency with the other asset types. So, for our perspective this is not a bug.

If you want you can create a SME request to clarify the behavoir, or if you want to share some feedback from the client you can create a PTR.

Regards,
Eudaldo.

**Comment by IstvanD** [comment]
Hey @ealonso 

Thank you for your reply.
What I did, is testing the behavior for various asset types, Blogs, Wikis, Message Boards, Web Content in their "own" portlets, not in Asset Publisher.
So I added Blogs portlet, Wiki portlet, Message Board portlet to a page, subscribed to them as another user ( let's say UserA), and created and modified Blogs, Wiki pages, MB Threads etc. in their own respective portlet.
As UserA, I clicked on the titles of the notifications about the creation/modification of the entries, and I was redirected to the entry in question, not a list view, as for Web Contents.
I think so far this is OK as Web Contents are meant to be viewed in a dedicated Web Content Display portlet, which is optional for Articles having one.
On the other hand, Web Contents can be configured to be viewed on a specific page, in a specific Asset Publisher portlet.
If a user has set up a Web Content that way, than, IMO it would be intuitive for this Article to be rendered on this page and not as an item among the other entries.

Please let me know what are your opinions about this approach.
Thank you!

Best regards,
István

**Comment by ealonso** [comment]
see: https://github.com/liferay/com-liferay-journal/pull/567

**Pull request closed without merging**
