### PR TITLE
LPS-68885 Fix JournalArticleLocalServiceImpl to avoid unnecessary rem…

### PR DESCRIPTION
**Pull request by shuyangzhou**
…ove and readd, it won't work with new tx model, as there will be no more hidden session flush

CC @brianchandotcom

### CODE REVIEW

**Comment by juliocamarero** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by shuyangzhou** [comment]
@juliocamarero when will this change be synced to master? I have following changes depend on this. Not until it is synced, I can not continue my work. Thanks!

**Comment by juliocamarero** [comment]
https://github.com/liferay/liferay-portal/pull/1056

I don't have permissions to merge that, only Brian :(

let me send him an email.

**Comment by shuyangzhou** [comment]
Thanks @juliocamarero !

**Pull request merged**
